\section{Conclusion}

In this paper, we present a novel method for authoring cutaway illustrations made from mesoscopic biological 3D models. To monitor and fine-tune the process, we introduce the visibility equalizer. It keeps the user informed about the ratios of the molecular instances removed by the clipping objects, or occluded from the current viewpoint. Moreover, the visibility equalizer allows the users to directly change these ratios by interacting with the visibility equalizer, thus fine-tuning the visibility of the individual molecular ingredients within the visualized scene.

The proposed method allows the illustrators to create high quality illustrations from the pre-packed biological models in a reasonable amount of time. This was confirmed by gathering feedback from the professional illustrators, as well as by recreating existing illustrations with our method. While being simple to use, the method gives the user a considerable level of artistic freedom.

The conceptual contribution of this work is demonstration of a scenario where a visualization metaphor, such as the stacked bar chart in our case, can serve as a user interface for performing a specific task, in our case authoring a cutaway design. We expect to see further cases where the (information) visualization acts simultaneously as the user interface.


%During the whole authoring process, our method keeps the user informed about the ratios of the molecular instances removed by the clipping objects, or occluded from the current viewpoint. 

