\section{Related Work}
[overview of related areas]

\subsection{Visualization of Molecular Structures}
\cite{cellVIEW_2015}
-this work is based on cell view

-refs from cellview papers

-only short overview

\subsection{Occlusion Management}
\begin{itemize}
	\item overview of techniques based on Elmqvist survey - motivation for occlusion handling - argumentation for different techniques
	\item cutaway techniques: volumetric \& polygon approaches
	\item other techniques: transparency,..
	
\end{itemize}
\cite{Viola05}
\cite{Burns07}
\cite{Burns08}
\cite{Li07}
\cite{Lidal12}

\subsection{Visual Steering}
[coffey et al  - design by dragging]

[additional refs from coffey paper]
