%\section{Background}
%[here we give more detail about the stuff that we couldnt talk about in more detail in the introduction \&\& that is \textbf{background information} essential for understanding/following the rest of the paper.]

%\subsection{animated transitions in molecular biology}=>>> this should be handled in the intro..
%for what kind of knowledge transfer are they used (examples)?
%why are they essential?

%\subsection{illustration in molecular visualization}
%todo: discuss background of field \& application of illustration
%\textbf{(todo: outsource to Graham)}
%basically ask him to tell us in his words (justify \& motivate), why animations such as in his award winning video are such a great tool for communication scientific insights. (doesnt matter if its verbose, we can shorten it.)
%and also ask him to write a bit about the background of his field. what his tasks as illustrator \& animator are, who are his customers / users, where does he get his data from, what does the data look like, what do his users/customers want to see?


		


