\section{Related Work}
[todo: add relevant papers from related work folder]
\begin{itemize}
	\item story telling: 
	\item interpolation between spaces/representations: A space(Balabanian)
	\item animation / animated transitions: heer \& schneiderman, 
	\item alternatives to animated transtions: small multiples, coordinated multiple views (CMV), static image (infographic) with glyphs that encode the change
\end{itemize}

	

	\textbf{infographics:} assisted with glyphs and labels

		\textbf{small multiples: }represent essential snapshots (points) in time, static.
		while tversky argues, small multiples or static images can be as powerful in conveying the transition as animations, it is hard to design them so that they contain all the information that a viewer needs to follow along.
			e.g., in case of badly designed instruction manuals, users often switch to youtube video when they cannot follow the thread.			
		it is not really known, at which intervals / what kind of keyframes in the transition are essential to guarantee the viewer's understanding (true?).
			generally, it could be said, the less images are used in the small multiples - the more rich the information that they encode needs to be
			

	these go basically from analytical towards engaging \& from interactive towards non-interactive. the suitability of a method depends on the user's task / what he wants to achieve / to present.