
%% If you are submitting a paper to a conference for review with a double
%% blind reviewing process, please replace the value ``0'' below with your
%% OnlineID. Otherwise, you may safely leave it at ``0''.
\onlineid{0}

%% declare the category of your paper, only shown in review mode
\vgtccategory{Technique}

%% allow for this line if you want the electronic option to work properly
\vgtcinsertpkg

%% In preprint mode you may define your own headline.
%\preprinttext{To appear in an IEEE VGTC sponsored conference.}

%% Paper title.

\title{TRANNI -- TRANsitions aNImated: A Formalization of Animated Transitions in Illustrative Molecular Biology}

%% This is how authors are specified in the journal style

%% indicate IEEE Member or Student Member in form indicated below
\author{A, B, and C}
\authorfooter{
%% insert punctuation at end of each item
\item
 Author A is with Institute X. E-mail: a@x.com.
\item
 Author B is with Institute Y. E-mail: b@Y.com.
}

%other entries to be set up for journal
\shortauthortitle{TRANNIES }
%\shortauthortitle{Firstauthor \MakeLowercase{\textit{et al.}}: Paper Title}

%% Abstract section.
\abstract{...todo...

} % end of abstract

%% Keywords that describe your work. Will show as 'Index Terms' in journal
%% please capitalize first letter and insert punctuation after last keyword
\keywords{...todo..}

%% ACM Computing Classification System (CCS). 
%% See <http://www.acm.org/class/1998/> for details.
%% The ``\CCScat'' command takes four arguments.

\CCScatlist{ ..todo..
}
